### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by anderson916** [rnpm/rnpm#110]
```
rnpm-link info Linking react-native-code-push android dependency
rnpm-link info Android module react-native-code-push is already linked
rnpm-link info Linking react-native-code-push ios dependency
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:34
    log.warn(
    ^

ReferenceError: log is not defined
    at registerNativeModuleIOS (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:34:5)
    at /usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by anderson916** [comment]
using the latest rnpm 1.5.2

**Comment by grabbou** [comment]
Good catch! Hint: create group called `Libraries` in your xcode project in the meantime, shipping fix right now.

https://developer.apple.com/library/ios/recipes/xcode_help-structure_navigator/articles/Creating_a_Group.html

**Comment by grabbou** [comment]
Please `npm install rnpm -g` again, error should be fixed in 1.6.1 rnpm-plugin-link :)

**Comment by anderson916** [comment]
Another error:

```
rnpm-link info Linking react-native-code-push android dependency
rnpm-link info Android module react-native-code-push is already linked
rnpm-link info Linking react-native-code-push ios dependency
rnpm-link WARN ERRGROUP Group Libraries does not exist in your XCode project. We have created it automatically for you.
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9
  return libraries.children.push({
                  ^

TypeError: Cannot read property 'children' of null
    at addProjectToLibraries (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9:19)
    at registerNativeModuleIOS (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:46:3)
    at /usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by anderson916** [comment]
I am using xcode workspace because of using cocoapods. Is this the reason?

**Comment by Kureev** [comment]
@anderson916 can you create a new issue with this error?

**Comment by grabbou** [comment]
Shouldn't be the reason, I'll check later today.
