### ISSUE TITLE
rnpm link Error IOS with Cocoapods

### ISSUE THREAD

**Issue by jerson** [rnpm/rnpm#114]
Hi im trying link my deps
1) create my React native app 
```
react-native init MyApp
```
2) install libs
```
npm install lib1 lib2
```
3) link
```
rnpm link
# this okkkk .. but then.. 
```
4) add cocoapods
```
cd ios && pod init
#then add some pod libs
```
5) pod install libs
```
cd ios && pod install
# install ok
```
6) try app
```
react-native run-ios
# this okk
```
7) try link again
```
rnpm link
#errror :/

rnpm-link info Linking react-native-material-kit android dependency 
rnpm-link info Android module react-native-material-kit is already linked 
rnpm-link info Linking react-native-material-kit ios dependency 
rnpm-link info iOS module react-native-material-kit has been successfully linked 
rnpm-link info Linking react-native-vector-icons android dependency 
rnpm-link info Android module react-native-vector-icons is already linked 
rnpm-link info Linking react-native-vector-icons ios dependency 
rnpm-link info iOS module react-native-vector-icons has been successfully linked 
rnpm-link info Linking realm android dependency 
rnpm-link info Android module realm is already linked 
rnpm-link info Linking realm ios dependency 
rnpm-link info iOS module realm has been successfully linked 
rnpm-link info Linking assets to ios project 
/usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/getPlistPath.js:8
    .replace(/"/g, '')
    ^

TypeError: Cannot read property 'replace' of undefined
    at getPlistPath (/usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/getPlistPath.js:8:5)
    at linkAssetsIOS (/usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/copyAssets.js:17:56)
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:63:5
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:262:13)
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:274:29
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:44:16
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:723:17
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at /usr/local/Cellar/node/5.8.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:52:16

```

**Comment by grabbou** [comment]
Thanks, this is getting fixed, see -> https://github.com/rnpm/rnpm-plugin-link/issues/41
