### ISSUE TITLE
Not working with cocoapod: TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by itinance** [rnpm/rnpm#118]
When cocoapods will be added to a RN-project, rnpm link gives the following error:

![screen shot 2016-03-24 at 10 51 12](https://cloud.githubusercontent.com/assets/1758597/14013825/fb189498-f1ae-11e5-852b-d2a4a0e20cfa.png)

```
$ rnpm link
rnpm-link info Linking react-native-vector-icons android dependency 
rnpm-link info Android module react-native-vector-icons is already linked 
rnpm-link info Linking react-native-vector-icons ios dependency 
rnpm-link WARN ERRGROUP Group Libraries does not exist in your XCode project. We have created it automatically for you.
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9
  return libraries.children.push({
                  ^

TypeError: Cannot read property 'children' of null
    at addProjectToLibraries (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9:19)
    at registerNativeModuleIOS (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:46:3)
    at /usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:516:17)
```

**Steps to reproduce:**

1. create rn-app and cd init it
`$ react-native init my-test-app && cd my-test-app`

2. install a plugin like: 
`$ npm install react-native-vector-icons --save`

3. $ rnpm link
```
rnpm-link info Linking react-native-vector-icons android dependency 
rnpm-link info Android module react-native-vector-icons is already linked 
rnpm-link info Linking assets to android project 
rnpm-link info Assets has been successfully linked to your project 
```
(everything works fine here)

4. initialize cocoapods:
`$ pod init && pod install`
_(it doesn't matter here, if zero or more pods has been installed)_

5. another call to "rnpm link" breaks it:
```
$ rnpm link
rnpm-link info Linking react-native-vector-icons android dependency 
rnpm-link info Android module react-native-vector-icons is already linked 
rnpm-link info Linking react-native-vector-icons ios dependency 
rnpm-link WARN ERRGROUP Group Libraries does not exist in your XCode project. We have created it automatically for you.
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9
  return libraries.children.push({
```
 
(see complete error message and callstack above)

**My versions:**
```
$ react-native -v
react-native-cli: 0.1.10
react-native: 0.22.2
$ npm -v
3.7.3
$ pod --version
0.39.0
xcode:  7.2.1 (7C1002)
```

**More hints**
It does'nt matter if initially "rnpm link" is executed before "pod init" or if you start with cocoapods and run "rnpm link" some time later. Thus you can skip step 3 and you will receive the same error.

**Comment by grabbou** [comment]
Hey, thanks for reporting. What is your `rnpm` version?
