### ISSUE TITLE
rnpm link error

### ISSUE THREAD

**Issue by L-Jovi** [rnpm/rnpm#121]
I call `rnpm link` receive below output, I think I already have __Libraries__ group in XCode :(

![error](https://cloud.githubusercontent.com/assets/7262199/14070156/7f5cb2ba-f4d5-11e5-91ea-21856f777070.png)

any ideas?  thanks for your time.

```
rnpm-link WARN ERRGROUP Group Libraries does not exist in your XCode project. We have created it automatically for you.
/Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9
  return libraries.children.push({
                  ^

TypeError: Cannot read property 'children' of null
    at addProjectToLibraries (/Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9:19)
    at registerNativeModuleIOS (/Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:46:3)
    at /Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
    at /Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/Users/mengwenqiaoxindongcom/.nvm/versions/node/v5.4.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by grabbou** [comment]
This issue has been fixed recently (not yet released) and will be released today. I think we are looking for a different `Libraries` group (is that a top-level group in your project or a nested one?).

The message indicates there's no such top-level group. I will release it in next 3 hours so please do let me know later if the problem persists (and if not - let me know what group we did created because it looks like we might be looking for `Libraries` in not all places)

**Comment by L-Jovi** [comment]
I'll upgrade when you released :)

**Comment by grabbou** [comment]
1.5.3 is out - try it out and let me know :)

**Comment by L-Jovi** [comment]
@grabbou  it works well now,  thanks :)
