### ISSUE TITLE
TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by wzywno** [rnpm/rnpm#126]
Hi,
When I run  `rnpm link` I get
```
rnpm-link info Linking react-native-facebook-login android dependency 
rnpm-link info Android module react-native-facebook-login is already linked 
rnpm-link info Linking react-native-facebook-login ios dependency 
rnpm-link WARN ERRGROUP Group Libraries does not exist in your XCode project. We have created it automatically for you.
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9
  return libraries.children.push({
                  ^

TypeError: Cannot read property 'children' of null
    at addProjectToLibraries (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addProjectToLibraries.js:9:19)
    at registerNativeModuleIOS (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:46:3)
    at /usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/usr/local/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

In my xcode project I had Libraries group before.
<img width="243" alt="screen shot 2016-03-31 at 10 18 44" src="https://cloud.githubusercontent.com/assets/1249754/14169775/084ae7e4-f72a-11e5-8d6d-b69cfa0b9415.png">

**Comment by grabbou** [comment]
Hey, are you on the latest version? We have fixed that recently!
