### ISSUE TITLE
ReferenceError: pjson is not defined

### ISSUE THREAD

**Issue by sibeliusseraphini** [rnpm/rnpm#147]
```js
v6.0.0/lib/node_modules/rnpm/src/findPlugins.js:22
    Object.keys(pjson.dependencies || {}),
                ^

ReferenceError: pjson is not defined
    at e (/Users/sibelius/.nvm/versions/node/v6.0.0/lib/node_modules/rnpm/src/findPlugins.js:22:17)
    at Array.map (native)
    at findPlugins (/Users/sibelius/.nvm/versions/node/v6.0.0/lib/node_modules/rnpm/src/findPlugins.js:35:31)
    at getCommands (/Users/sibelius/.nvm/versions/node/v6.0.0/lib/node_modules/rnpm/src/getCommands.js:16:7)
    at Object.<anonymous> (/Users/sibelius/.nvm/versions/node/v6.0.0/lib/node_modules/rnpm/bin/cli:7:47)
```

I'm receiving this error on node 6.0.0 with the latest version of rnpm link

**Comment by almasakchabayev** [comment]
Can you release a new version please. I keep getting this error. Thanks

**Comment by sibeliusseraphini** [comment]
@almasakchabayev you can do this for now:

```bash
git clone git@github.com:rnpm/rnpm.git
cd rnpm
npm link
npm link rnpm # this will use your local version instead of npm version
```

You will also need to do this to with https://github.com/rnpm/rnpm-plugin-link

**Comment by grabbou** [comment]
@almasakchabayev AFAIK @Kureev is planning to do a release today (Alexey - if you dont have time then let me know and I'll just send patch to rnpm itself)

**Comment by michaeljgilmore** [comment]
@grabbou eager to get this fix as well.

**Comment by grabbou** [comment]
It's already in npm :)

**Comment by bradennapier** [comment]
still broken? 
```

/usr/local/lib/node_modules/rnpm/src/findPlugins.js:22
    Object.keys(pjson.dependencies || {}),
                ^

ReferenceError: pjson is not defined
    at e (/usr/local/lib/node_modules/rnpm/src/findPlugins.js:22:17)
    at Array.map (native)
    at findPlugins (/usr/local/lib/node_modules/rnpm/src/findPlugins.js:35:31)
    at getCommands (/usr/local/lib/node_modules/rnpm/src/getCommands.js:16:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/rnpm/bin/cli:8:47)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by grabbou** [comment]
No, it's not :) https://github.com/rnpm/rnpm/blob/master/src/findPlugins.js#L15-L17

Please update to latest.

**Comment by bradennapier** [comment]
I installed it 5 minutes before posting?

**Comment by Kureev** [comment]
Which version are you using, @bradennapier?

**Comment by Kureev** [comment]
You have a problem with `pjson`, @bradennapier ?

**Comment by bradennapier** [comment]
I did until I realized above that the file I had was up to date which made no sense - realized it was loading system version rather than nvm version so had to force uninstall system version.  Works now!  Thanks!
