### ISSUE TITLE
pjson is not defined

### ISSUE THREAD

**Issue by michaeljgilmore** [rnpm/rnpm#150]
/usr/local/lib/node_modules/rnpm/src/findPlugins.js:22
    Object.keys(pjson.dependencies || {}),
                ^

ReferenceError: pjson is not defined
    at e (/usr/local/lib/node_modules/rnpm/src/findPlugins.js:22:17)
    at Array.map (native)
    at findPlugins (/usr/local/lib/node_modules/rnpm/src/findPlugins.js:35:31)
    at getCommands (/usr/local/lib/node_modules/rnpm/src/getCommands.js:16:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/rnpm/bin/cli:7:47)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by grabbou** [comment]
Fixed in 1.6.4
