### ISSUE TITLE
ACCES: permission denied 

### ISSUE THREAD

**Issue by jojonarte** [rnpm/rnpm#174]
I'm having this weird issue on RNPM linking a component  Has anyone encountered this?

rnpm link react-native-vector-icons
/usr/local/lib/node_modules/rnpm/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/dna/.config/configstore/update-notifier-rnpm.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/rnpm/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/rnpm/node_modules/configstore/index.js:28:44)
    at new UpdateNotifier (/usr/local/lib/node_modules/rnpm/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/rnpm/node_modules/update-notifier/index.js:108:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/rnpm/bin/cli:11:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by Kureev** [comment]
Really weird. Looks like something is wrong with read permissions of your `'/Users/dna/.config/configstore/update-notifier-rnpm.json'`. Check if it's readable

**Comment by grabbou** [comment]
or just delete it & reinstall? ;) Anyway, please open an issue in update-notifier, might be a new bug.

**Comment by jojonarte** [comment]
I will check once i'm back on the office , I hope this is traceable.

**Comment by jojonarte** [comment]
Still the same occured :(

**Comment by Kureev** [comment]
Maybe `$ chmod +r /Users/dna/.config/configstore/update-notifier-rnpm.json` will do the trick?
