### ISSUE TITLE
[iOS] Unlink error : TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by mlumbroso** [rnpm/rnpm#196]
Here is full stack trace :

`sudo rnpm unlink react-native-branch
rnpm-link info Unlinking react-native-branch android dependency 
rnpm-link info Android module react-native-branch has been successfully unlinked 
rnpm-link info Unlinking react-native-branch ios dependency 
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeFromProjectReferences.js:14
  const projectRef = firstProject.projectReferences.find(item => item.ProjectRef === file.uuid);
                                                   ^

TypeError: Cannot read property 'find' of undefined
    at removeFromProjectReferences (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeFromProjectReferences.js:14:52)
    at removeProjectFromProject (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeProjectFromProject.js:17:22)
`

Thanks for your help :-)

**Comment by Kureev** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Hey @mlumbroso, we will be looking into this issue right after we merge our `rnpm` into react-native which shouldn't take more than a day now.

**Comment by mlumbroso** [comment]
Amazing, thanks for your reactivity :+1:
