### ISSUE TITLE
react native 0.16.0 different errors

### ISSUE THREAD

**Issue by alfonsodev** [rnpm/rnpm#46]
I'm getting cannot read properties when trying to run rnpm in this order : 

react-native init test
cd test/ 
npm install react-native-blur
rnpm link
```
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:55
    if (project.android && dependency.config.android) {
                                            ^

TypeError: Cannot read property 'android' of null
    at /usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:55:45
    at Array.forEach (native)
    at Object.link (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:54:16)
    at Command.runAction (/usr/local/lib/node_modules/rnpm/bin/cli:26:14)
    at Command.listener (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/rnpm/bin/cli:30:5)
Alfonsos-MacBook-Pro:app alfonso$ rnpm link react-native-blur
```
rnpm link react-native-blur
```
/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:72
      (assets, dependency) => assets.concat(dependency.config.assets),
                                    ^

TypeError: Cannot read property 'concat' of undefined
    at /usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:72:37
    at Array.reduce (native)
    at Object.link (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:71:18)
    at Command.runAction (/usr/local/lib/node_modules/rnpm/bin/cli:26:14)
    at Command.listener (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/rnpm/bin/cli:30:5
```

**Comment by radko93** [comment]
I have the same issue with `assets.concat`.

**Comment by grabbou** [comment]
Sorry, we forgot to publish 1.3.0 to npm :lollipop: Please `npm install -g rnpm` again and it will run flawlessly.
