### ISSUE TITLE
TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by sirvon** [rnpm/rnpm#98]
```nodejs
$ rnpm link react-native-code-push
rnpm info Linking react-native-code-push android dependency
rnpm info Android module react-native-code-push is already linked
rnpm info Linking react-native-code-push ios dependency
/usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/hasLibraryImported.js:7
  return libraries.children
                  ^
TypeError: Cannot read property 'children' of null
    at hasLibraryImported (/usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/hasLibraryImported.js:7:19)
    at registerNativeModuleIOS (/usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:26:7)
    at /usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
    at /usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/usr/local/opt/nvm/versions/node/v5.0.0/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by grabbou** [comment]
Thanks for the report. It sounds strange it still triggers an error (we handled it in the past), I'll take a look later today to see if I can reproduce

**Comment by Kureev** [comment]
so, is it reproducable, @grabbou?

**Comment by grabbou** [comment]
Yes, fixed in https://github.com/rnpm/rnpm-plugin-link/pull/34

PS @sirvon ensure you either have `Libraries` group in your XCode project (it should be created by default by react-native init) or make sure `libraryFolder` set in your rnpm config matches group you have.

Starting from next version, we will create it automatically for you, just like we create Resources group for assets.
